<a href="https://colab.research.google.com/github/nguyentrungtin123/thuchanh_deeplearning/blob/main/btlab02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

# Bài 3.1.1: Khởi tạo hằng số từ số nguyên
t1 = tf.constant(4)
print(t1)

# Bài 3.1.2: Khởi tạo từ danh sách (mảng 1 chiều)
t2 = tf.constant([1, 2, 3, 4])
print(t2)

# Bài 3.1.3: Khởi tạo mảng 2 chiều (ma trận)
t3 = tf.constant([[1, 2], [3, 4]])
print(t3)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [2]:
import tensorflow as tf

# Bài 3.2.1: Khởi tạo với kiểu số thực float32
t4 = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
print(t4)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [3]:
import tensorflow as tf
import numpy as np

# Bài 3.3.1: Chuyển mảng Numpy thành Tensor
arr = np.array([[1, 2, 3], [4, 5, 6]])
t5 = tf.convert_to_tensor(arr)
print(t5)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)


In [4]:
import tensorflow as tf

# Bài 3.4.1: Tạo ma trận toàn số 0
t6 = tf.zeros((3, 3))
print(t6)

# Bài 3.4.2: Tạo ma trận toàn số 1
t7 = tf.ones((2, 2))
print(t7)

# Bài 3.4.3: Tạo Tensor với một giá trị cụ thể (fill)
t8 = tf.fill((2, 3), 5)
print(t8)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5 5 5]
 [5 5 5]], shape=(2, 3), dtype=int32)


In [5]:
import tensorflow as tf

# Bài 3.5.1: Tạo ma trận đơn vị cấp 4
t9 = tf.eye(4)
print(t9)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [6]:
import tensorflow as tf

# Bài 3.6.1: Ngẫu nhiên theo phân phối chuẩn (Normal)
t10 = tf.random.normal((3, 3), mean=0, stddev=1)
print(t10)

# Bài 3.6.2: Ngẫu nhiên theo phân phối đều (Uniform)
t11 = tf.random.uniform((2, 2), minval=0, maxval=10)
print(t11)

tf.Tensor(
[[-0.17703803  0.06732204 -0.95559007]
 [-0.00438986  0.11982566 -0.63547444]
 [-0.45148987  0.38279247 -0.520655  ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1.9017923  0.2700162 ]
 [0.89628935 8.987873  ]], shape=(2, 2), dtype=float32)


In [7]:
import tensorflow as tf

# Bài 3.7.1: Khởi tạo Variable
v1 = tf.Variable([[1, 2], [3, 4]])
print(v1)

# Bài 3.7.2: Thay đổi giá trị của Variable (assign)
v1.assign([[5, 6], [7, 8]])
print(v1)

# Bài 3.7.3: Cộng thêm giá trị (assign_add)
v1.assign_add([[1, 1], [1, 1]])
print(v1)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 6],
       [7, 8]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[6, 7],
       [8, 9]], dtype=int32)>


In [8]:
import tensorflow as tf

t = tf.constant([[1, 2, 3], [4, 5, 6]])


print("Số chiều của Tensor:", t.ndim)


print("Hình dạng của Tensor:", t.shape)


print("Tổng số phần tử:", tf.size(t).numpy())


print("Kiểu dữ liệu:", t.dtype)

Số chiều của Tensor: 2
Hình dạng của Tensor: (2, 3)
Tổng số phần tử: 6
Kiểu dữ liệu: <dtype: 'int32'>


In [9]:
import tensorflow as tf

t = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


print(t[1].numpy())


print(t[1:5].numpy())


print(t[:3].numpy())

2
[2 3 4 5]
[1 2 3]


In [10]:
import tensorflow as tf

t2 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


print("Dòng 1:", t2[0, :].numpy())


print("Cột 2:", t2[:, 1].numpy())


print("Phần tử (1, 2):", t2[1, 2].numpy())

Dòng 1: [1 2 3]
Cột 2: [2 5 8]
Phần tử (1, 2): 6
